stat: add basic statistic
skd/telegram-bot-help-ua-ch pull request #19
Opened 2022-03-17 20:35 UTC by edganiukov

- number of active user
- number of total user
- node hits

So far all the stat stored in memory, so wont survive bot restarts.
Additionally dropped all the trailing whitespaces in textproto.

2022-03-17 21:52 UTC, skd reviewed
I have a feeling that you took the toughest snack! Also probably the most interesting. I left some comments.

2022-03-17 21:52 UTC, skd commented on conversation.proto
> +            string action = 2;
I don't really like that the special functionality leaks into a data model. I think we should keep this in the code.

2022-03-17 21:52 UTC, skd commented on bot.py
>      conv_handler = ConversationHandler(
Not yet sure, if that's a good idea, but we could define "/stats" as an entry_point (this would require to allow users somehow leave the conversation), or as a fallback.

2022-03-17 21:52 UTC, skd commented on bot.py
> +        if len(node_by_name[name].adminLink) > 0:
We could simply add the admin links to the starting node, which can be referred to with START_NODE.

2022-03-17 21:52 UTC, skd commented on bot.py
> +    "edgnkv",
Please add
@Zygimantas

2022-03-17 21:52 UTC, skd commented on bot.py
> +    bot_stat.dec_session()
This is unfortunately never called. We have decided to never let the users out of the ConversationHandler

2022-03-17 21:52 UTC, skd commented on bot.py
> +    bot_stat.inc_session()
I think this will work correctly by chance (I restart the bot once a day). I believe this is called once a user engages with the bot and then never again (unless the user session disappears from memory?)

If we want to track active users, I have a sense that we would have to store them somehow. Some kind of a bloomfilter maybe?

2022-03-17 21:52 UTC, skd commented on stats.py
> +class Stats:
Can we think of an easy way to track the stats over time? Like put it into hourly buckets, oslt?

2022-03-18 11:44 UTC, skd commented on bot.py
> +    "edgnkv",
Also @thecrdev

2022-03-18 16:37 UTC, crdev commented on stats.py
> +        nodes_stat = "\n".join(["\t- {}: {}".format(k, v) for k, v in self.node_hits.items()])
Could we use f-strings whenever appropriate? They seem to improve readability quite a bit (and they are also faster: https://realpython.com/python-f-strings/)

2022-03-18 16:49 UTC, crdev commented on bot.py
> +    bot_stat.dec_session()
A random idea: we could perhaps assume that a session ends after e.g. 30 minutes of inactivity. We could then have an LRU cache for each user id, timestamp renewed upon each interaction. Entries will be evicted and dec_session() called upon timeout.

2022-03-18 16:49 UTC, crdev commented on bot.py
> +    bot_stat.inc_session()
Would my idea above by chance work? :) Or is that too memory-taxing?

2022-03-19 10:49 UTC, edganiukov commented on bot.py
> +    bot_stat.dec_session()
I was thinking about LRU cache and keeping the data for 1 day in the cache. On `get_stat` we could return the number of user for the last 1h, 3h and 1 day. 
And doing clean-ups on new  insertion/updates.

2022-03-20 09:36 UTC, skd commented on bot.py
> +    bot_stat.dec_session()
I think that's a good idea. Especially, that it means that such a solution will not depend on calls to start() and done().

2022-03-20 12:46 UTC, crdev commented on bot.py
> +    bot_stat.dec_session()
Guys, it has taken me one evening and one night :) to implement session persistence in Redis (see https://github.com/crdev/telegram-bot-help-ua-ch/tree/test-prod). Redis has a great feature called key expiration (https://redis.io/commands/expire). Records will get removed after a specified "timeout". I suggest persisting nav stack changes upon every action and updating the expiration time to, let's say, +30 minutes or +1h - should be a good enough estimate of a "session" length. Then we could have a pubsub subscriber to get notifications about session expirations (https://help.heroku.com/5BP0E8RC/how-to-enable-notify-keyspace-events-on-redis) writing these (as start_timestamp + end_timestamp) into PostgreSQL. That would perhaps be done best with a worker job that could batch these and dump e.g. every minute or so (not sure how many user we have :-D). Ideas?

2022-03-20 20:12 UTC, edganiukov commented on bot.py
> +    "edgnkv",
done

2022-03-20 20:12 UTC, edganiukov commented on bot.py
>      conv_handler = ConversationHandler(
So in the end I've created simple `CommandHanlder` to handle `/stats`

2022-03-20 20:12 UTC, edganiukov commented on stats.py
> +class Stats:
Done, as we discussed - for each user interaction timestamp is getting updated, then it computes active user for the last 1h, 3h and 1d. I've decided do not clean-up it as we can use redis as @crdev suggested.
I was thinking to implement LRU, so computation would be faster, but in the end we would have more updates, rather then stats computation. But anyway - I would merge it and then try to optimize.

2022-03-20 20:13 UTC, edganiukov commented on bot.py
> +    bot_stat.dec_session()
so far I use simple hashmap (without any optimizations), lets use redis and see how we can optimize it

2022-03-21 12:02 UTC, edganiukov commented
Hi @skd anything else to address here? After this PR and https://github.com/skd/telegram-bot-help-ua-ch/pull/36 get merged, I will implement redis backend for metrics

2022-03-21 17:28 UTC, skd commented on bot.py
>      conv_handler = ConversationHandler(
Have you tested these changes? We removed the possibility to get out of ConversationHandler after one engaged into it (and any text engages in it). So, there will be very little possibilities to actually trigger /stats that would actually trigger the CommandHandler and not a fallback of ConversationHandler

2022-03-22 08:55 UTC, skd commented
Hi, not sure if you seen it, but there is one last comment to address.

2022-03-22 08:55 UTC, skd commented
Hi, not sure if you seen it, but there is one last comment to address.

2022-03-22 09:38 UTC, edganiukov commented on bot.py
>      conv_handler = ConversationHandler(
I do not have much experience with telegram bot, but I tested it (with latest master branch) and it works.

2022-03-22 13:31 UTC, edganiukov commented
> Hi, not sure if you seen it, but there is one last comment to address.

@skd you mean the one about `CommandHandler`? Yes, I've tested it, it works.

2022-03-22 14:51 UTC, crdev requested changes

2022-03-22 14:51 UTC, crdev commented on stats.py
>          self.users = dict()
self.timestamp_by_user ?

2022-03-22 14:51 UTC, crdev commented on stats.py
>  HOUR = 60*60
Would datetime.timedelta perhaps be a more useful type for these durations? timedelta.total_seconds() would be a less confusing way to get the seconds duration then... Multiplication by a scalar works the same way for timedeltas.

2022-03-22 16:21 UTC, edganiukov commented on bot.py
>      conv_handler = ConversationHandler(
Hm, even tho it did work, but now I added "Statistics" button as a part of `/start` node (but only for admin users).

2022-03-22 16:22 UTC, edganiukov commented on stats.py
>          self.users = dict()
done

2022-03-22 16:22 UTC, edganiukov commented on stats.py
>  HOUR = 60*60
done

2022-03-22 22:49 UTC, skd approved these changes

2022-03-22 22:49 UTC, skd commented on bot.py
> +    "zygimantas",
Zygimantas (it's case sensitive)

I don't have access to push to your branch. :)

2022-03-22 22:49 UTC, skd commented
Thank you, it's looking good!

2022-03-23 08:44 UTC, merged